name: Update Infra
on:
  push:
    branches:
      - main
jobs:
  up:
    name: Update
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      
      - name: Install Pulumi CLI
        uses: pulumi/action-install-pulumi-cli@v1.0.1
      
      - run: npm install
      
      - uses: pulumi/actions@v2
        with:
          command: up
          stack-name: dev
          work-dir: .pulumi
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}

      - run: pulumi stack output kubeconfig --show-secrets > ~/kubeconfig

      - uses: actions/upload-artifact@v2
        with:
          name: kubeconfig
          path: kubeconfig
  
  
  install-linkerd:
    name: Install Linkerd
    runs-on: ubuntu-20.04
    needs:
      - up
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: kubeconfig
          path: kubeconfig
      
      - run: echo ./kubeconfig
  
      # - uses: azure/setup-kubectl@v1
      #   with:
      #     version: '1.20.5' # default is latest stable
      #   id: install

      # - uses: actions/checkout@v2
      #   with:
      #     fetch-depth: 1
      

      # - name: Deploy to Kubernetes cluster
      #   run: 
