name: Update Infra
on:
  push:
    branches:
      - main
jobs:
  up:
    name: Create Cluster
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1   
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install Pulumi CLI
        uses: pulumi/action-install-pulumi-cli@v1.0.1
      - run: npm install
      - uses: pulumi/actions@v2
        with:
          command: up
          stack-name: dev
          work-dir: .pulumi
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}

      - run: pulumi stack output kubeconfig --show-secrets > ./kubeconfig
        working-directory: .pulumi

      - uses: anthonykgross/ansible-vault-cli-github-action@v1
        with:
          vault_key: ${{ secrets.ANSIBLE_VAULT_KEY }}
          command: "ansible-vault encrypt .pulumi/kubeconfig"

      - uses: anthonykgross/ansible-vault-cli-github-action@v1
        with:
          vault_key: ${{ secrets.ANSIBLE_VAULT_KEY }}
          command: "chmod 444 .pulumi/kubeconfig"

      - run: ls -la .pulumi

      - uses: actions/upload-artifact@v2
        with:
          name: kubeconfig
          path: .pulumi/kubeconfig
  
  
  install-linkerd:
    name: Install Linkerd
    runs-on: ubuntu-20.04
    needs:
      - up
    steps:
      - uses: azure/setup-kubectl@v1
        with:
          version: 'v1.20.5' # default is latest stable
        id: install

      - uses: actions/download-artifact@v2
        with:
          name: kubeconfig
          path: .

      - uses: anthonykgross/ansible-vault-cli-github-action@v1
        with:
          vault_key: ${{ secrets.ANSIBLE_VAULT_KEY }}
          command: "ansible-vault decrypt kubeconfig"
      
      - uses: anthonykgross/ansible-vault-cli-github-action@v1
        with:
          vault_key: ${{ secrets.ANSIBLE_VAULT_KEY }}
          command: "chmod 444 kubeconfig"

      - run: |
          mkdir -p ~/.kube
          mv kubeconfig ~/.kube/config

      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      
      - name: Deploy to Kubernetes cluster
        run: kubectl apply -f .k8s/manifests